[workspace]
authors = ["Hiroyuki Shinnou <hiroyuki.shinnou.0828@vc.ibaraki.ac.jp>"]
channels = ["conda-forge"]
name = "mragbook"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
datasets = ">=5.0.0,<6"
langchain-text-splitters = ">=1.1.2,<2"
faiss-cpu = ">=1.10.0,<2"
pypdf2 = ">=3.0.1,<4"
huggingface_hub = "<1"
openai = ">=2.41.1,<3"
pdf2image = ">=1.17.0,<2"

[pypi-dependencies]
sentence-transformers = ">=5.5.1, <6"
accelerate = ">=1.14.0, <2"
docling = ">=2.102.1, <3"
colpali-engine = ">=0.3.13, <0.4"
